version: '3.1'

services:
  jmodelica:
    build: 
      context: './jmodelica'
      args:
        testcase: testcase2
    ports:
     - "127.0.0.1:5000:5000"
    image: "boptest_testcase"
    command: python /usr/testcases/restapi.py
    network_mode: host
  julia:
    build: ./julia
    command: julia /usr/myapp/szvav-sup.jl
    network_mode: host